import logging
import os
import shutil
import stat
import sys
import tempfile
from contextlib import contextmanager
from pathlib import Path
from torch_memory_saver.hooks.base import HookUtilBase
from torch_memory_saver.utils import get_binary_path_from_package, change_env

logger = logging.getLogger(__name__)

# Path to the non-setgid Python binary copy (created lazily)
_nosuid_python_path = None

# Temp dir holding the sitecustomize.py for subprocess TMS loading (created lazily)
_sitecustomize_dir = None


def _get_nosuid_python() -> str:
    """
    Return path to a Python binary without the setgid/setuid bit.

    On some systems (e.g. Baidu PaddleJob containers), the conda Python binary
    has the setgid bit set (-rwxrws---), which causes glibc's dynamic linker to
    silently ignore LD_PRELOAD.  We create a temporary copy of the binary with
    the sticky bits stripped so that LD_PRELOAD works correctly.

    Returns the path to the current interpreter if it is already clean.
    """
    global _nosuid_python_path

    executable = sys.executable
    # Resolve symlinks to get the real binary
    real_exec = os.path.realpath(executable)

    file_stat = os.stat(real_exec)
    has_suid = bool(file_stat.st_mode & stat.S_ISUID)
    has_sgid = bool(file_stat.st_mode & stat.S_ISGID)

    if not has_suid and not has_sgid:
        # Already clean, no copy needed
        return executable

    if _nosuid_python_path is not None and os.path.exists(_nosuid_python_path):
        return _nosuid_python_path

    # Create a copy in a tmpdir (persists for the lifetime of the process)
    tmp_dir = tempfile.mkdtemp(prefix="tms_python_")
    nosuid_path = os.path.join(tmp_dir, "python")
    shutil.copy2(real_exec, nosuid_path)
    # Remove setuid and setgid bits
    current_mode = os.stat(nosuid_path).st_mode
    new_mode = current_mode & ~(stat.S_ISUID | stat.S_ISGID)
    os.chmod(nosuid_path, new_mode)

    logger.info(
        f"Created non-setgid Python copy at {nosuid_path} "
        f"(original: {real_exec}, had suid={has_suid}, sgid={has_sgid})"
    )
    _nosuid_python_path = nosuid_path
    return nosuid_path


def _get_sitecustomize_dir(tms_so_path: str) -> str:
    """
    Create (once) a temporary directory containing a sitecustomize.py that
    loads the TMS shared library via ctypes.CDLL(..., RTLD_GLOBAL) before any
    other user imports happen.

    This is necessary on environments (e.g. Baidu CGpu containers) where the
    kernel/container runtime strips LD_PRELOAD from child process environments,
    making the classic LD_PRELOAD approach ineffective.
    """
    global _sitecustomize_dir

    if _sitecustomize_dir is not None and os.path.isdir(_sitecustomize_dir):
        return _sitecustomize_dir

    tmp_dir = tempfile.mkdtemp(prefix="tms_sitecustomize_")
    sc_path = os.path.join(tmp_dir, "sitecustomize.py")

    # Write sitecustomize.py; it runs before any user code in the subprocess.
    # RTLD_GLOBAL (0x100 on Linux) makes the symbols globally visible so that
    # they override the real cudaMalloc/cudaFree when paddle is imported later.
    with open(sc_path, "w") as f:
        f.write(f"""\
# Auto-generated by torch_memory_saver configure_subprocess()
# Loads TMS shared library before paddle/torch so that cudaMalloc is intercepted.
import ctypes as _ctypes
import os as _os

_tms_so_path = _os.environ.get("TMS_SO_PATH", {tms_so_path!r})
if _tms_so_path:
    try:
        _ctypes.CDLL(_tms_so_path, mode=_ctypes.RTLD_GLOBAL)
    except Exception as _e:
        import sys
        print(f"[torch_memory_saver sitecustomize] WARNING: failed to load TMS so: {{_e}}", file=sys.stderr)
""")

    logger.info(f"Created TMS sitecustomize.py at {sc_path} for TMS so: {tms_so_path}")
    _sitecustomize_dir = tmp_dir
    return tmp_dir


class HookUtilModePreload(HookUtilBase):
    def get_path_binary(self):
        # Prefer TMS_SO_PATH env var (set by configure_subprocess via sitecustomize approach)
        tms_so_path = os.environ.get("TMS_SO_PATH", "")
        if tms_so_path and "torch_memory_saver" in tms_so_path:
            return tms_so_path

        # Fallback: classic LD_PRELOAD approach
        env_ld_preload = os.environ.get("LD_PRELOAD", "")
        interest_paths = [p for p in env_ld_preload.split(":") if "torch_memory_saver" in p]
        assert len(interest_paths) == 1, (
            f"TorchMemorySaver observes invalid LD_PRELOAD or TMS_SO_PATH. "
            f"You can use configure_subprocess() utility, "
            f"or directly specify `LD_PRELOAD=/path/to/torch_memory_saver_cpp.some-postfix.so python your_script.py. "
            f'(LD_PRELOAD="{env_ld_preload}" TMS_SO_PATH="{tms_so_path}" process_id={os.getpid()})'
        )
        return interest_paths[0]


@contextmanager
def configure_subprocess():
    """Configure subprocesses to load TMS before paddle. Only needed for hook_mode=preload."""
    import multiprocessing.spawn as _mp_spawn

    tms_so_path = str(get_binary_path_from_package("torch_memory_saver_hook_mode_preload"))
    nosuid_python = _get_nosuid_python()
    sitecustomize_dir = _get_sitecustomize_dir(tms_so_path)

    # Override PYTHONPATH so Python picks up our sitecustomize.py first.
    orig_pythonpath = os.environ.get("PYTHONPATH", "")
    if orig_pythonpath:
        new_pythonpath = sitecustomize_dir + ":" + orig_pythonpath
    else:
        new_pythonpath = sitecustomize_dir

    # multiprocessing.spawn uses _mp_spawn._python_exe (set at import time from sys.executable).
    # We must call set_executable() to override it for spawned subprocesses when nosuid is needed.
    orig_mp_exe = _mp_spawn.get_executable()
    need_replace_executable = (
        nosuid_python != orig_mp_exe and
        nosuid_python != os.path.realpath(orig_mp_exe)
    )

    try:
        if need_replace_executable:
            _mp_spawn.set_executable(nosuid_python)
            logger.debug(f"configure_subprocess: set multiprocessing executable to {nosuid_python}")

        # Set TMS_SO_PATH so the sitecustomize.py can read it (and as a signal to get_path_binary)
        # Also keep LD_PRELOAD as a belt-and-suspenders fallback for non-CGpu environments.
        os.environ["PYTHONPATH"] = new_pythonpath
        os.environ["TMS_SO_PATH"] = tms_so_path
        with change_env("LD_PRELOAD", tms_so_path):
            yield
    finally:
        if need_replace_executable:
            _mp_spawn.set_executable(orig_mp_exe)
        os.environ["PYTHONPATH"] = orig_pythonpath
        if "TMS_SO_PATH" in os.environ:
            del os.environ["TMS_SO_PATH"]
